### ISSUE TITLE
Update version number

### ISSUE THREAD

**Issue by chabou-san** [reedog117/node-vsphere-soap#11]
First of all, I want to thank you for your work. It's already really useful to me.

I'm currently using [yarn](https://yarnpkg.com) to manage my dependencies. The thing is it is stricter about semver than npm.
So the fact that you named your current version `0.0.2-5` means that it's a pre-version of `0.0.2` (much like `0.0.2-beta.1` or so).
If you're interested in it, you can learn about the rules here : http://semver.org
Anyhow, it causes yarn  to pick the version `0.0.2` of your package when using `node-vsphere` instead of your last version `0.0.2-5`. This is also due to your way of declaring your dependency in `node-vsphere` where `"node-vsphere-soap": "^0.0.2-5"` means that it shall pick any version superior or equal to `0.0.2-5`. And `0.0.2` does.
There is a workaround for me which is to add directly the dependency to `node-vsphere-soap` among the _direct_ dependencies of my project. But I would really like to avoid that.
It is possible for you to either rename your version (not the best way to deal with the problem), or rather release a new version (such as a `0.0.3-1` ?)

**Comment by patcbuilds** [comment]
I haven't had time to update this module in forever, but submit a pull
request and I'll approve it.

patrick correa
patrickc81@gmail.com

**Comment by chabou-san** [comment]
Ok, thanks a lot.
